/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth/route'
import { Route as AuthIndexImport } from './routes/_auth/index'
import { Route as AuthUsuariosPerfilImport } from './routes/_auth/usuarios/perfil'
import { Route as AuthUsuariosAdminImport } from './routes/_auth/usuarios/admin'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthUsuariosPerfilRoute = AuthUsuariosPerfilImport.update({
  id: '/usuarios/perfil',
  path: '/usuarios/perfil',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthUsuariosAdminRoute = AuthUsuariosAdminImport.update({
  id: '/usuarios/admin',
  path: '/usuarios/admin',
  getParentRoute: () => AuthRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/usuarios/admin': {
      id: '/_auth/usuarios/admin'
      path: '/usuarios/admin'
      fullPath: '/usuarios/admin'
      preLoaderRoute: typeof AuthUsuariosAdminImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/usuarios/perfil': {
      id: '/_auth/usuarios/perfil'
      path: '/usuarios/perfil'
      fullPath: '/usuarios/perfil'
      preLoaderRoute: typeof AuthUsuariosPerfilImport
      parentRoute: typeof AuthRouteImport
    }
  }
}

// Create and export the route tree

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthUsuariosAdminRoute: typeof AuthUsuariosAdminRoute
  AuthUsuariosPerfilRoute: typeof AuthUsuariosPerfilRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthUsuariosAdminRoute: AuthUsuariosAdminRoute,
  AuthUsuariosPerfilRoute: AuthUsuariosPerfilRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/': typeof AuthIndexRoute
  '/usuarios/admin': typeof AuthUsuariosAdminRoute
  '/usuarios/perfil': typeof AuthUsuariosPerfilRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthIndexRoute
  '/usuarios/admin': typeof AuthUsuariosAdminRoute
  '/usuarios/perfil': typeof AuthUsuariosPerfilRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/usuarios/admin': typeof AuthUsuariosAdminRoute
  '/_auth/usuarios/perfil': typeof AuthUsuariosPerfilRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/login' | '/' | '/usuarios/admin' | '/usuarios/perfil'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/usuarios/admin' | '/usuarios/perfil'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/'
    | '/_auth/usuarios/admin'
    | '/_auth/usuarios/perfil'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/login"
      ]
    },
    "/_auth": {
      "filePath": "_auth/route.tsx",
      "children": [
        "/_auth/",
        "/_auth/usuarios/admin",
        "/_auth/usuarios/perfil"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/": {
      "filePath": "_auth/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/usuarios/admin": {
      "filePath": "_auth/usuarios/admin.tsx",
      "parent": "/_auth"
    },
    "/_auth/usuarios/perfil": {
      "filePath": "_auth/usuarios/perfil.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
